[package]
name = "netan-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[[bin]]
name = "netan"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
netan-api = { path = "../api" }
netan-core = { path = "../core" }
netan-ingest = { path = "../ingest" }
netan-persist = { path = "../persist" }
netan-profile = { path = "../profile" }
netan-query = { path = "../query" }
netan-report = { path = "../report" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
