[package]
name = "netweevil-ingest"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
netweevil-core = { path = "../core" }
netweevil-persist = { path = "../persist" }
netweevil-report = { path = "../report" }
osmpbfreader.workspace = true
sha2.workspace = true

[lints]
workspace = true
