[package]
name = "netan-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
netan-core = { path = "../core" }
netan-persist = { path = "../persist" }
netan-profile = { path = "../profile" }
netan-query = { path = "../query" }
netan-report = { path = "../report" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
